# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np
X = np.zeros(100)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
Y = np.ones(100)
print(Y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
Z = np.full(100, 3)
print(Z)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [31]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 5. Создать вектор со значениями от 10 до 100

In [5]:
Z = np.arange(10,100)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [6]:
Z = np.arange(0,16).reshape(4,4)
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [15]:
Z = np.random.random((3,3))
print(Z)

[[0.00522174 0.17922635 0.07447503]
 [0.80639993 0.99473901 0.1218368 ]
 [0.11584284 0.25524033 0.52661454]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [16]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.47076781 0.69239604 0.29970198]
  [0.48840562 0.5384379  0.82437653]
  [0.59336729 0.23669575 0.51770136]]

 [[0.0187438  0.20067305 0.74631006]
  [0.93428155 0.80649585 0.96277504]
  [0.01577078 0.61448772 0.17302505]]

 [[0.20987453 0.76966113 0.87682501]
  [0.25589128 0.68980408 0.17793723]
  [0.00464985 0.7560451  0.72318098]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [22]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

[[0.32506425 0.16333976 0.25440956 0.23541468 0.88148932 0.20673349
  0.08433489 0.1666509  0.14649851 0.23623074]
 [0.50862405 0.56798195 0.79643609 0.24480209 0.6480594  0.35919535
  0.5457969  0.70057046 0.66209616 0.24041713]
 [0.12482201 0.96703816 0.25022985 0.24918339 0.98807874 0.68720489
  0.93798181 0.57522207 0.22071546 0.79021035]
 [0.55212924 0.40476523 0.74437787 0.83710096 0.88818126 0.79158685
  0.74703785 0.79941749 0.17533435 0.85428568]
 [0.21804031 0.17844383 0.25610447 0.24411421 0.00518059 0.61559719
  0.04276052 0.36627916 0.97380275 0.52916742]
 [0.26398139 0.69721492 0.70386561 0.71340564 0.95943209 0.31279712
  0.56085721 0.36249524 0.17697053 0.62600773]
 [0.02411221 0.46863491 0.18431327 0.4370294  0.45388366 0.212951
  0.85759097 0.32076811 0.43171653 0.91575264]
 [0.99684757 0.26904166 0.03861347 0.28672898 0.61433392 0.69393094
  0.81307883 0.43212914 0.90272204 0.94705562]
 [0.33012568 0.38919889 0.8738851  0.69206586 0.6919856  0.33236895
  0.64150214 0

#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [23]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.35878138001741516


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [24]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [29]:
Z = np.arange(11)
print(Z)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [30]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [33]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)

[[0.72649087 0.19158868 0.4441254  0.42743156 0.6105297  0.44309897
  0.02538531 0.5192807  0.7919444  0.17965848]
 [0.03600227 0.37585884 0.79385946 0.89635806 0.7068677  0.26530522
  0.43174025 0.31662079 0.70220973 0.66318318]
 [0.65052882 0.41551202 0.08330814 0.44497889 0.27566962 0.39476307
  0.51227152 0.25461863 0.9293334  0.82648815]
 [0.49733947 0.19622496 0.92063256 0.7605364  0.71567547 0.04669572
  0.38030976 0.73236153 0.05601802 0.19800199]
 [0.63062082 0.64985695 0.35685965 0.07825358 0.52670062 0.93073212
  0.20971883 0.88018425 0.2229083  0.18080009]]
[[ 0.29053746 -0.24436473  0.00817199 -0.00852185  0.1745763   0.00714557
  -0.4105681   0.08332729  0.35599099 -0.25629493]
 [-0.48279828 -0.14294171  0.27505891  0.37755751  0.18806715 -0.25349533
  -0.0870603  -0.20217976  0.18340918  0.14438263]
 [ 0.17178159 -0.0632352  -0.39543909 -0.03376833 -0.20307761 -0.08398416
   0.03352429 -0.22412859  0.45058618  0.34774092]
 [ 0.04695988 -0.25415462  0.47025297  0.31015681